### ISSUE TITLE
dat_path parameter not working?

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#102]
It used to be possible to create a params.py file located in the folder where all the .npy are, and specify where the data file are with a dat_path parameter. However, the solution does not seem to be working anymore. For example, the following params.py file, created in the folder where some results are, and launched with 

>> phy template-gui params.py

does not work. What am I doing wrong? 

```
dat_path       = '../../testdata.dat'
n_channels_dat = 30
n_features_per_channel = 5
dtype          = 'int16'
offset         = 0
sample_rate    = 20000
hp_filtered    = True
```

Best

Pierre

**Comment by rossant** [comment]
what is the error message?

**Comment by yger** [comment]
No but I think I'm just confused, I should rather use dir_path. I think my
ticket is useless, let me check

Pierre

2017-03-16 14:01 GMT+01:00 Cyrille Rossant <notifications@github.com>:
