### ISSUE TITLE
CorrelogramView

### ISSUE THREAD

**Issue by brunoEm** [kwikteam/phy-contrib#108]
I was wondering why no y-axis was implemented in the correlogramview - wouldn't the magnitude of the correlation be an useful piece of information? Also, I know it's circumstance-dependent, but what kind of bin/window size setting would be best advised? I would be very interested to know what other people use and how they interpret what they see. Cheers!

**Comment by Artemissy** [comment]
I agree, a y-Axis would be helpful to estimate the percentage of contamination in the refractory period. 
(Kwik-Gui user here).

I  use default settings. 1 ms bin size to properly evaluate the refractory gap. Increasing window size would make sense when looking for periodic spiking.  For example responses to an event in repeating trials. Or for sparsely spiking neurons. But I do not see how this is relevant for sorting.

**Comment by rossant** [comment]
there is now a baseline firing rate in the dev branch of phy
