### ISSUE TITLE
Channels with largest amplitude events for sparse waveforms

### ISSUE THREAD

**Issue by balefebvre** [kwikteam/phy-contrib#110]
Recently I notice a little bug, under certain conditions (see below) the channels with largest amplitude events in the ClusterView and SimilarityView are inconsistent with the channel numbers displayed in the WaveformView.

I observed this behavior when I display some data produced by the converting method of SpyKING CIRCUS with the sparse export option set to true. If I set the sparse option to false then everything is fine.

To illustrate this bug, here is a screenshot without the sparse option (i.e. without bug)

![phycontrib github issue channels dense](https://cloud.githubusercontent.com/assets/2544801/25534404/f97fde50-2c33-11e7-81d9-a9f71d697c24.png)

and here is a screenshot with the sparse option (i.e. with bug)

![phycontrib github issue channels sparse](https://cloud.githubusercontent.com/assets/2544801/25534414/ff3773c6-2c33-11e7-9b5a-b0c949ae0163.png)

Best!

**Comment by rossant** [comment]
should be fixed in the dev branch of phy
