### ISSUE TITLE
new view: waveform stack

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#113]
This is an idea borrowed from jrclust (see https://www.youtube.com/watch?v=8ocPRXt6lCg, the one called "averaged waveform sample" in left-center). It's for a new view that may help to visualize the results of sorting and to speed up manual sorting. It's not a replacement for existing waveform view - I'm not proposing anything change about that view. 

In this new view, each cluster would get a single column (so channels are just ordered by depth, even if this confuses/hides their X-position). The mean waveform (or template) is shown, and perhaps also some sample waveforms. The clusters are ordered by depth. This makes it easy to see at a glance something like what you see with similarity view, i.e. the presence of nearby similar clusters. It also provides a nice way to get an overview of all of your clusters across the probe, for which there isn't really any good solution currently. Noise clusters disappear from this view, whereas MUA just become grey (every other cluster can be, e.g., white - then the selected one(s) can take appropriate colors). This sort of view wouldn't really work at all for a square-shaped probe like Pierre's retinal MEAs, I think, but many/most people use linear or tetrode-like probes and it should work for all of those. 

Not sure this is very high priority but I do think it'd be useful, and I heard from at least one person that this view was so useful that it led them to prefer using jrclust over kilosort, just for this gui difference.

**Comment by greggheller** [comment]
When we tried out jrclust this view was the one thing that I preferred about their GUI. It was especially useful for picking out drifted spikes that don't register with a high similarity score. So I definitely second this as a useful addition.

**Comment by rossant** [comment]
done in the dev branch of phy ("template view")
