### ISSUE TITLE
how to change number of channels shown in waveform view? 

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#118]
Hey @rossant, I can't [re-]figure out how to change the number of channels that are shown in waveform view. I found [the line in model.py](https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/template/model.py#L171) that I thought would set this property, but changing it didn't seem to do anything, even after deleting the .phy folder, and it doesn't look like there's anything in ~/.phy that would override that. Suggestion for how to achieve this now? Thanks -

**Comment by rossant** [comment]
added in the documentation
