### ISSUE TITLE
How to analyze data after using the template-gui

### ISSUE THREAD

**Issue by madeleinea** [kwikteam/phy-contrib#119]
I'm wondering how to use (and access) the data after editing sorted data in the template-gui. After manually sorting out our data, we typically use the Plexon software NeuroExplorer, which can take in text and Matlab files. I know that spike_clusters.npy and cluster_groups.csv are created after saving in the template-gui, and I'm wondering if those could be used for further analysis.

Specifically, what is the spike_clusters.npy files and how can I access that data? If it contains information about the units and timestamps, then converting it to a text file might be our solution. 

Any advice would be greatly appreciated!

**Comment by nsteinme** [comment]
Please see the documentation here (
https://github.com/kwikteam/phy-contrib/blob/master/docs/template-gui.md)
for a description of all the files. They can be loaded with numpy in Python
or with npy-matlab (https://github.com/kwikteam/npy-matlab) in Matlab. Then
they could be written to text files or analyzed directly. Let us know if
that doesn't answer your question?

**Comment by madeleinea** [comment]
Thanks, that helps a lot. Looking at the documentation, I'm still unclear on one thing: Does spike_clusters.npy contain spike timestamps?

**Comment by nsteinme** [comment]
Nope, that's in spike_times.npy. spike_clusters is the cluster number
associated with every spike. So if you are looking at cluster 10 in phy,
then to get the spike times of that cluster, what you want (in matlab) is:
>> spike_times(spike_clusters==10)

**Comment by madeleinea** [comment]
Great, that works! How do I export the waveforms for each unit?

**Comment by nsteinme** [comment]
You're in luck, we just added a function to the [spikes](https://github.com/cortex-lab/spikes) repository that will do this in matlab: [getWaveforms.m](https://github.com/cortex-lab/spikes/blob/master/analysis/getWaveForms.m). Thanks @goatsofnaxos. In python, this is the method phy uses to do it, I think: [_get_waveforms](https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/template/gui.py#L233).
