### ISSUE TITLE
A way to pull the channel number associated with each cluster?

### ISSUE THREAD

**Issue by madeleinea** [kwikteam/phy-contrib#120]
Hi, I'm trying to associate each cluster with the channel it came from in Matlab, but I can't figure out which file will have the information. I know that it's there, because the template-gui is able to display the channel number for each cluster, I just can't figure out where it's getting that information. Let me know!

**Comment by nsteinme** [comment]
The template gui shows the channel that has the largest amplitude in the
template. The templates are stored in templates.npy, which has a matrix
nTemplates x nTimepoints x nChannels. So you can take the maximum across
timepoints for each channel in the template of interest, then find the
largest channel.

**Comment by madeleinea** [comment]
Great, thank you. And in this case, each template corresponds to... each unit?

**Comment by nsteinme** [comment]
Did you get here after running kilosort, or maybe spyking circus? In either case, these algorithms use a "template matching" procedure - you should consider checking out the related publication to get an idea of how they work and what the template is. In any case, you could do instead the same procedure (finding the maximum channel) on the mean waveform that was extracted as in your other question.

**Comment by madeleinea** [comment]
I used kilosort. So your suggestion mostly works, except for when the clusters are edited in phy, and new clusters are created with IDs that extend beyond the template.npy parameters. Is there a way around that issue?

**Comment by nsteinme** [comment]
Yes, you want to determine the template for the new cluster that was
created. What I usually do is take the template identities for all the
spikes (spike_templates.npy) of the new cluster, and determine which
template is most numerous among these. Then I take that template. Since you
will have merged only similar templates, this will be representative.
