### ISSUE TITLE
Mac Template GUI View Problems

### ISSUE THREAD

**Issue by DJ-Hayden** [kwikteam/phy-contrib#121]
Hello, 

I've attached a picture of the data created from the KiloSort tutorial, and the TraceView seems to be slightly off compared to the pictures I've seen everywhere. Is this a bug in the code or is there an option I need to select?
![kilosort pic png](https://user-images.githubusercontent.com/28391906/29007213-3a9747ac-7acc-11e7-9a05-7a099ebaf368.png)

**Comment by nsteinme** [comment]
Try bringing the vertical scaling down a bunch of times - see the trace
view menu, I think the hotkey is alt+- or alt+down, can't remember off the
top of my head. At some point they should at least stop being vertical
lines, then you can tell whether is real data or whether the file was
loaded poorly or something.

**Comment by DJ-Hayden** [comment]
That solved the problem! For posterity the problem was as follows:

You may see:

![figure1](https://user-images.githubusercontent.com/28391906/29033910-985e289a-7b64-11e7-9465-8e1793009250.png)

Use TraceView -> Go To -> (Some time into recording, say 20 seconds).

Then you may see: 

![figure2](https://user-images.githubusercontent.com/28391906/29033955-b78fde3e-7b64-11e7-905e-a42646f03b03.png)

Use TraceView -> Narrow repeatedly to get a few second time window (say 1-2 seconds). Keyboard shortcuts help.

![figure3](https://user-images.githubusercontent.com/28391906/29034011-d866a4da-7b64-11e7-90e7-321a98b30733.png)

Use TraceView -> Decrease repeatedly to get the picture to look like the following picture. Keyboard shortcuts help.

![figure4](https://user-images.githubusercontent.com/28391906/29034068-0849c916-7b65-11e7-80af-373507f3f8a9.png)
