### ISSUE TITLE
traceview: overlapping colors

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#126]
It's sometimes confusing when a spike appears one color when all spikes are highlighted, but it turns out not to "really" be that color - that's just the color of some distant neuron that happens to include that channel on the edge, and the distant neuron gets painted on top of the central one. In the screenshot below, all four of the big spikes should be blue (they are in the selected cluster) but only two of them do, because the others were painted over by a different color. There are multiple resolutions to this, in order of simplicity:
1) Make the selected cluster's blue color always paint on top
2) Make the top color be the color of the cluster with the closest peak channel
3) Make the top color be the color of the cluster with the largest amplitude at that time on that channel
4) Have the colors fade as a function of amplitude, and blend or else choose the top one based on which has largest amplitude

Should at least do the first one, for clarity!

**Comment by nsteinme** [comment]
Here are the screenshots I meant to include:
![image](https://user-images.githubusercontent.com/7590975/29265522-494a4ad4-80d9-11e7-9eb5-bacebc6809a8.png)

![image](https://user-images.githubusercontent.com/7590975/29265541-538884d4-80d9-11e7-8de9-5b75a326a43c.png)

**Comment by rossant** [comment]
I think this is resolved on the dev branch of phy
