### ISSUE TITLE
WaveformView

### ISSUE THREAD

**Issue by KatalinS** [kwikteam/phy-contrib#129]
Hi Everyone,
I have a problem with the WaveformView. When I started to use the KiloSort, everything was fine. After that something happened (maybe I used a wrong key combinations or I don't know). Now I am not able to see  the channels separeted in the WaveformView. I think that all channels are in one channel (All channels are collected in the last channel). I use 16 and 32 channels probe, I tried it with file which it showed normally the channels before but now it doesn't want to work too.  I attached a picture of this problem.  
![kilosort](https://user-images.githubusercontent.com/31208926/29517406-40644a36-8675-11e7-8f07-080d1898d6d5.PNG)

I hope someone can help me :) 
Kati

**Comment by nsteinme** [comment]
Try shrinking the waveforms many times (ctrl+down arrow) until it looks
close to flat then use the right click+drag to separate out the channels?
The other possibility is that your channel_positions.npy file got lost or
got changed. It needs to specify the locations of the channels at different
positions. You can also try deleting the .phy folder in the working
directory and in your user directory, then re-open phy on this dataset
(this will reset all the views).

**Comment by neuRowsATL** [comment]
HI Katalin,

I was able to reproduce your issue by holding down CTRL + <right> for way too long... To recover from the problem, I just held down CTRL + <left> for more than way too long... That separated the columns into different waveforms. Then, you'll need to extend the vertical spread of the waveforms by holding SHFT + <up>. On both accounts, I had to hold the keys down for about 3-5 seconds before I started to see anything begin to change.

Like nsteinme said, you may also need to check your .prb or channel_poisitions.npy file to make sure that they are arrange appropriately for the GUI.

**Comment by rossant** [comment]
also, you could try to delete the `~/.phy/TemplateGUI/state.json` file
