### ISSUE TITLE
Error: No such command "kwik-gui"

### ISSUE THREAD

**Issue by vncntprvst** [kwikteam/phy-contrib#13]
Hi,
I installed klusta, phy and phy contrib in a conda environment on Windows 7. When I run "phy kwik-gui hybrid_10sec.kwik", it returns:
`Error: No such command "kwik-gui"`

I've forced an upgrade on phycontrib, just to check - no difference.

The output from >phy kwik-gui --debug is:
```
23:55:56 [D] config:45            Load config file `C:\Users\Vincent\.phy\phy_config.py`.
23:55:56 [D] plugin:35            Register plugin `__builtin__.MyPlugin`.
23:55:56 [D] cli:87               Attach plugin `__builtin__.MyPlugin` to CLI.
Usage: phy [OPTIONS] COMMAND [ARGS]...

Error: No such command "kwik-gui".
```
I'm not sure if that's the issue, but phy_config.py is in C:\Users\Vincent\.phy\ and the kwik_gui folder is found in C:\Anaconda\envs\klusta\Lib\site-packages\phycontrib. However, adding the relevant directories to PATH does not solve the issue.

**Comment by rossant** [comment]
phy_config should be in ~/.phy
Le 27 mars 2016 06:34, "Vincent Prevosto" <notifications@github.com> a
écrit :

**Comment by rossant** [comment]
What is the contents of the file `C:\Users\Vincent\.phy\phy_config.py`? You can try to delete the entire directory `~/.phy` and install phycontrib again. 

Another solution is just to put `import phycontrib` somewhere in `phy_config.py`

The way it works is that `phy` looks for plugins in folders specified in `c.Plugins.dirs` in the `~/.phy/phy_config.py` file, which by default points to `~/.phy/plugins`, and `phycontrib` copies a little Python script containing just `import phycontrib` in there. This way, all phycontrib plugins are automatically loaded when you import phy.

**Comment by rossant** [comment]
@vncntprvst is this fixed now?

**Comment by vncntprvst** [comment]
It works now, by adding `import phycontrib ` in `phy_config.py`. 
The issue derive from the fact that the directory ~/.phy/plugins/ is not created when installing phy or phycontrib, so phy cannot find the relevant plugins. Adding `import phycontrib ` is fine as a workaround, but of course doesn't fix the original issue.

**Comment by rossant** [comment]
OK, I will fix that by adding `import phycontrib` in the default `phy_config.py`.
