### ISSUE TITLE
Split units in waveform view?

### ISSUE THREAD

**Issue by madeleinea** [kwikteam/phy-contrib#130]
Hi, is there a way to split clusters in waveform view, not just in featureview? This would be really helpful to finish sorting our data.

**Comment by neuRowsATL** [comment]
Hi Madeleinea,

I started using the Klusta Suite of spike sorting tools last year and have been working on some customizations for our own analyses. I have not come across a way to split clusters in WaveformView, but your point caught my attention as it could prove to be a handy tool -- or even to select a waveform and go to that point in time. In fact, while I'm thinking about it, it would be nice to be able to also show different subsets of waveforms to get a better idea of the quality of matching within a cluster.

Anyhow, can you elaborate a little about how you would use the WaveformView to split a cluster? In other words, can you describe how you would imagine clicking on waveforms or in open spaces to set thresholds or find the closest matching shapes?

Alternatively, what about being able to plot different parameters, such as waveform amplitude, and then sorting by using a feature-like view (i.e., a scatter plot)?

**Comment by rossant** [comment]
might not be needed now that splitting is enabled in the amplitude view and spike attribute views (in the dev branch of phy)
