### ISSUE TITLE
Shading and background waveforms in WaveformView

### ISSUE THREAD

**Issue by weallen** [kwikteam/phy-contrib#131]
I noticed that the TemplateGUI WaveformView in some of the example images on the phy-contrib github page show the waveforms for each cluster apparently shaded by their average amplitude for each electrode, and with what appear to be background waveforms in grey:
![image](https://user-images.githubusercontent.com/526501/30675073-3b6783ec-9e33-11e7-9a51-5661f3982360.png)

Whereas the version of TemplateGUI I'm using (TemplateGUI v1.0.9, phycontrib v1.0.15) simply shows a subset of the electrodes with no shading:
![image](https://user-images.githubusercontent.com/526501/30675205-0cf55fce-9e34-11e7-9b60-787f6310cc45.png)

Was this a feature of an older version of the software, or does this feature not work on certain systems?

**Comment by nsteinme** [comment]
Older version. For speed, the newer version omits distant channels. I'm
hoping the number of channels displayed can become set-able though!
