### ISSUE TITLE
missing "stack' attribute

### ISSUE THREAD

**Issue by vncntprvst** [kwikteam/phy-contrib#134]
Hi all,
Just re-posting this Kilosort related issue here: 
https://github.com/cortex-lab/KiloSort/issues/94#event-1341896657

> after opening the output params.py from the "eMouse" test data in phy, the cluster data are shown (CorrelogramView, FeatureView, etc) , but when selecting a cluster, the WaveformView does not show anything, and the command prompt says:
> [E] cli:36 An error has occurred (AttributeError): 'module' object has no attribute 'stack'

Nick suggested to update **numpy**, which I did although it already was up-to-date, but that didn't help.
Also, note that running `phy template-gui params.py --debug` returns `Error: no such option: --debug`
Any help appreciated.

**Comment by nsteinme** [comment]
phy template-gui params.py --debug works for me - are you sure you have the
environment activated - it runs without that option? Otherwise I'm even
more confused, cyrille will have to help I think, sorry...

**Comment by vncntprvst** [comment]
Yep, environment activated, and it runs without that option. I know, weird. Thanks for trying to help though.

**Comment by rossant** [comment]
And what about `phy --debug template-gui params.py` ?

**Comment by vncntprvst** [comment]
Same outcome. `no such option: --debug`

**Comment by rossant** [comment]
There might be a conflict between several incompatible versions of phy... I don't see any other reason why `--debug` would not work.

**Comment by vncntprvst** [comment]
I agree. I did a complete cleanup (pip and conda uninstall + manual removal from Conda directories, including .\AppData\Local\conda\) then reinstall with `pip install git+https://github.com/kwikteam/phy git+https://github.com/kwikteam/phy-contrib` . Still get the same issue.

**Comment by rossant** [comment]
what are the output of:
* `phy --version`
* `which phy`
* `python -c "import phycontrib; print(phycontrib.__file__)"`

**Comment by vncntprvst** [comment]
Here are the output (I just replaced "which" by "where", its equivalent on Windows)
```
phy --version
phy, version 1.0.9

where phy
C:\ProgramData\Anaconda2\envs\spkc27\Scripts\phy.exe

python -c "import phycontrib; print(phycontrib.__file__)"
C:\ProgramData\Anaconda2\envs\spkc27\lib\site-packages\phycontrib\__init__.pyc
```

**Comment by mjk1028** [comment]
hi there,

i also encountered the same issue - showing no waveforms when a cluster is selected. i attach a screen shot after running 'phy template-gui params.py --debug'.

i am not sure this is causing not showing waveforms but that is what i have now. thank you for your helps in advance!

![screenshot_2017-11-21_23-09-48](https://user-images.githubusercontent.com/30392701/33109698-1c6ba1d0-cf11-11e7-85c4-15ab1a173322.png)

**Comment by nsteinme** [comment]
@mjk1028 I am fairly sure your problem is caused by an old version of numpy, please try upgrading it. This exact same thing happened to me. @vncntprvst sorry still not sure in your case, though you could try to determine what version of numpy is installed in the spkc27 environment. It needs to be at least 1.10 I think.

**Comment by mjk1028** [comment]
@nsteinme  thank you nick, for your answer but when i check the numpy version, it is '1.13.3'. is it still old version? when i try to upgrade, it won't since it seems the latest version of numpy.

**Comment by vncntprvst** [comment]
Ha, thanks Nick, that was the missing information. By default Conda only updates **numpy** to 1.9. So I added conda-forge: `conda config --add channels conda-forge` . Then installed numpy (which also triggered updating of a bunch of packages), and re-installed phy & phy-contrib for good measure. That fixes the  `missing "stack' attribute ` issue, and WaveformView is back to normal. The `no such option: --debug` persists, but that's another problem. You may want to consider suggesting in the documentation to add the conda-forge channel in case of package version issues. Thanks for your help everyone.

**Comment by nsteinme** [comment]
@mjk1028 please try the method for upgrading that vincent suggests? If it doesn't work, re-open issue maybe.
