### ISSUE TITLE
Any latest progress of Phy-contrib?

### ISSUE THREAD

**Issue by WaveformDai** [kwikteam/phy-contrib#135]
Hi,

I'm recently using Phy along with KiloSort to do spike sorting. Several problems occurred to me and most of them  have already been reported in different issues. Nevertheless, I'm still kind of confused and I decide to post a new issue hoping to know any latest developmental progress of Phy.

My problems (and some (unsolved?) corresponding issues) are:

1) reading from raw data instead of creating a new copy of binary data like posted in https://github.com/kwikteam/phy-contrib/issues/63. I don't know if  https://github.com/kwikteam/phy-contrib/issues/83  means that this has already been accomplished. If so, where can I find trace-gui?

2) enable template splitting from waveform view directly --- https://github.com/kwikteam/phy-contrib/issues/95 https://github.com/kwikteam/phy-contrib/issues/130. This is the step that some commercial/custom spike sorting software is taking.

3) add more fields in cluster view and even a histogram of amplitude in amplitude view --- https://github.com/kwikteam/phy-contrib/issues/30 https://github.com/kwikteam/phy-contrib/issues/16. Current version of phy only provide depth information, but for 2D/3D array, additional xcoords/ycoords would definitely help visualization. Other labels, like firing rate, SNR, group information are also helpful. It's obvious that some users have done this. But I'm not familiar with python, so I hope anyone that has successfully added these features may give me some suggestions. Attached figures are some examples(adapted from https://github.com/cortex-lab/KiloSort/issues/65).

![wechat image_20171121165422](https://user-images.githubusercontent.com/14290870/33063557-c01656a6-cedd-11e7-8929-c543896d4035.png)
![1511254483 1](https://user-images.githubusercontent.com/14290870/33063564-c657f75e-cedd-11e7-81cf-43fe2649d431.jpg)

4) Idea of @nsteinme in https://github.com/kwikteam/phy-contrib/issues/40 is also interesting and I'd like to know whether this has already been achieved?

Any help/suggestions will really be appreciated and many thanks for help develop/maintain so wonderful a tool for spike sorting!

.

**Comment by rossant** [comment]
I've been busy with other projects for a while but development of phy should continue soon! Thank you for your suggestions.

**Comment by xf123chen** [comment]
Hi,WaveformDai,
I come from china and use the multi-channel recording systems. I try to setup this software, but didn't success. can you help me,thanks. xf123chen@163.com

**Comment by rossant** [comment]
(1) see https://github.com/cortex-lab/phylib/issues/5
(2) one can now split in the amplitude view which should be sufficient
(3) done in the dev branch of phy
