### ISSUE TITLE
No groups column or channel display

### ISSUE THREAD

**Issue by rjp109** [kwikteam/phy-contrib#136]
Hello,

I have installed phy/phy-contrib on a new computer to work with kilosort. However when loading my params.py using the template-gui there is no 'groups' column in ClusterView and also there is no window that displays the channels/shanks of my array. I have these features on another computer I was using, is there perhaps a different version of phy/phy-contrib to download?

**Comment by rossant** [comment]
the shank information is not part of the latest version, follow-up here https://github.com/cortex-lab/phy/issues/782
