### ISSUE TITLE
Features plotting intermittently with multiple data files

### ISSUE THREAD

**Issue by neuRowsATL** [kwikteam/phy-contrib#139]
## Illustrating the Issue
There appears to be an error in the plotting or analysis of points in the FeatureView with multiple data files. In the first example, the features plotted over time have breaks in which no spikes are detected (**Fig 1**).

_**Figure 1.** Intermittency issue in FeatureView._
![slide1](https://user-images.githubusercontent.com/16469819/36109472-8a341644-0fed-11e8-8fad-6fd6fbae517c.JPG)

Here are a couple of other examples from the same dataset. In these examples, it appears as though spikes were detected throughout the full duration of the dataset, but events within and across discrete periods of time were clustered separately. For example, tracking red (**Fig 2**) or orange (**Fig 3**).

_**Figure 2.** Intermittency issue with FeatureView separates similar spikes across discrete time periods. Compare green and red clusters to orange cluster._
![slide2](https://user-images.githubusercontent.com/16469819/36109631-f40dd6b8-0fed-11e8-9ee4-c7de81c6cdae.JPG)

_**Figure 3.** Intermittency issue with FeatureView separates spikes across discrete time periods. Clusters may be similar (or not) and are still separated across data files. Compare green and orange clusters to magenta and brown clusters._
![slide3](https://user-images.githubusercontent.com/16469819/36109635-f7170cbc-0fed-11e8-93ef-4ff8060a681f.JPG)

## Describing the Data
There are 80 data files with 1 minute of data each. The algorithm was run using the Klusta Conda Environment. When I run a subset of data with 20 files (1 minute each) the features plot correctly without the intermittent spaces. Also, when I run the same 20-file subset of data as one 20 minute data file the intermittency problem does not occur.

## Preliminary Troubleshooting
I plotted the File # (from the index in KWIK file) as a function of the spike ID (from the ID of spikes in KWIK file) to see if there was a relation between the file ID and the missing spikes. The resulting plot showed that the red and blue clusters (**Fig 3** bottom two rows) occurred in only a few data files (no spikes occurred in files that are not listed to the right of the plot). The black, magenta, green, and orange clusters, however, were missing spikes in the same data files that the red and blue spikes were found. Also, there appeared to be a pattern in the files that were aberrant... 23, 34, 45, 56, 67, 78 -- all cases where the two digits are consecutive.

_**Figure 4.** File ID plotted as a function of Spike ID shows pattern in FeatureView intermittency. NOTE: These clusters are not the same as the clusters in Fig 1-3._
![slide5](https://user-images.githubusercontent.com/16469819/36110380-69e78fb2-0ff0-11e8-9246-7836b06ec990.jpg)

Finally, I checked the indices and file names in the KWIK file. The indices of the files as well as the time stamps are all increasing correctly in the HDF5 KWIK file:
/recordings/#
/recordings/#.name
/recordings/#.start_sample
/recordings/#.start_time
/recordings/#/raw.dat_path

_**Figure 5.** Table of indices, time stamps, and data files in KWIK file._
![slide4](https://user-images.githubusercontent.com/16469819/36110329-345d75dc-0ff0-11e8-94eb-fcb59d21eb02.jpg)

## **Anyone experiencing the same thing?**
- Could this be an issue caused by the SpikeDetekt algorithm -- I did not track the data and indices through/into the SpikeDetekt class.
- Could this be an issue caused by the multi-threading of the clustering step?
- Any other suggestions for a possible cause?

**Comment by rossant** [comment]
to reopen in the klusta repository if needed
