### ISSUE TITLE
Splitting clusters from WaveformView

### ISSUE THREAD

**Issue by vncntprvst** [kwikteam/phy-contrib#14]
This is a feature enhancement request: 
As I understand it, splitting clusters only works based on a selection made in Feature view. It would be nice (and effectively quicker sometimes) to be able to split clusters in WaveformView as well.

**Comment by rossant** [comment]
This would be quite hard to implement, if ever possible, because we only have access to a handful of the waveforms. Doing this would require to load *all* waveforms from all clusters, which would be way to expensive.

**Comment by vncntprvst** [comment]
I see. I was wondering if all waveforms were available, actually. So this answers two questions at once :)
