### ISSUE TITLE
Disable noisy electrodes

### ISSUE THREAD

**Issue by julienschuermans** [kwikteam/phy-contrib#140]
Hi,

is there a way to disable certain electrodes in both the TraceView and the WaveformView?
It sometimes happens in my HD-sEMG datasets that there are a couple very noisy traces due to bad contact with the skin. These traces mess up the scaling of the others.
How can I remove them from the plots?
![screen shot 2018-03-04 at 20 44 15](https://user-images.githubusercontent.com/14927054/36949747-dc9b792c-1fec-11e8-8fcd-174681626d75.png)

**Comment by rossant** [comment]
open a new "option to ignore bad channels in phy" issue in the phy repo if needed
