### ISSUE TITLE
Can't reopen closed windows in template-gui

### ISSUE THREAD

**Issue by xigumalu** [kwikteam/phy-contrib#144]
I accidentally closed the ProbeView window and can't open again. Right-clicking on the header of other windows brings up a list of all windows including ProbeView with tick marks on those that are open. Unfortunately, the tick marks cannot be clicked/closed windows cannot be opened again.

**Comment by rossant** [comment]
You can reset the disposition of the windows by renaming `~/.phy` to `~/.phy~` and relaunching the GUI.
