### ISSUE TITLE
Location of depth info

### ISSUE THREAD

**Issue by Tran0311** [kwikteam/phy-contrib#148]
Hello,

I would like to ask from which file generated from the kilosort can we find the channel from which the clusters have the highest depth value? We can see the values on the manual clustering template but are not sure in which file the information is stored.

Best regards,

**Comment by nsteinme** [comment]
See documentation about the contents of the files here:
http://phy-contrib.readthedocs.io/en/latest/template-gui/

You can use the templates.npy matrix to calculate the amplitude of each
template on each channel, and from there find the channel with the max
amplitude for each template. For each cluster you will need to identify
which template best represents it (by comparing spike_clusters and
spike_templates).

Or, you can load the waveforms of example spikes directly from the file for
the spike times you know, and then apply the procedure above.

**Comment by nsteinme** [comment]
You need to calculate them yourself by finding the peak channel. They are
not stored explicitly, sorry.

**Comment by Tran0311** [comment]
I see. Thanks!

**Comment by rossant** [comment]
in the dev branch of phy, the `cluster_info.tsv` is automatically saved with all information contained in the cluster view. That includes the "best" (peak) channel for every cluster.
