### ISSUE TITLE
Bug in auto-correlogram display

### ISSUE THREAD

**Issue by llobetv** [kwikteam/phy-contrib#149]
Hi,

I really like phy but i encounter some issue when phy show auto-correlogram, sometime it show me some aberrant auto, here 1 auto which is really nice with phy and totally bad if i make the auto myself :
![image](https://user-images.githubusercontent.com/22896067/40069384-a9645622-585a-11e8-87a8-f3a1f1b05cdc.png)
compare to :
![image](https://user-images.githubusercontent.com/22896067/40069412-c2dbdc9c-585a-11e8-8f45-423edae2ef04.png)

there is several case like that an other exemple: 
![image](https://user-images.githubusercontent.com/22896067/40069663-821df9c8-585b-11e8-9ea8-6b04c04be7ba.png)

and
![image](https://user-images.githubusercontent.com/22896067/40069700-95e55c9e-585b-11e8-87ec-9763a5a900b3.png)

And finally a cross corr between 2 cluster from the same neuron :
![image](https://user-images.githubusercontent.com/22896067/40070797-a8d1db90-585e-11e8-9252-82eba65da636.png)

I run phy kwik-gui with ubuntu 16.04.
here list of package in my env : 

cairo                     1.14.6                        0  
click                     6.6                      py27_0  
colorama                  0.3.7                    py27_0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
decorator                 4.0.10                   py27_1  
enum34                    1.1.6                    py27_0  
fontconfig                2.12.1                        0  
freeglut                  2.8.1                         0  
freetype                  2.5.5                         1  
glib                      2.50.2                        0  
h5py                      2.6.0               np110py27_1  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.16                        0  
ipython_genutils          0.1.0                    py27_0  
joblib                    0.9.4                    py27_0  
klusta                    3.0.16                    <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libxml2                   2.9.4                         0  
matplotlib                1.5.1               np110py27_0  
mkl                       11.3.3                        0  
mpi4py                    2.0.0                    py27_2  
mpich2                    1.4.1p1                       0  
numpy                     1.10.4                   py27_2  
openssl                   1.0.2j                        0  
pango                     1.40.3                        0  
pcre                      8.39                          1  
phy                       1.0.9                     <pip>
phycontrib                1.0.15                    <pip>
pip                       10.0.1                    <pip>
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
progressbar2              3.6.1                    py27_0    spyking-circus
psutil                    5.0.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pyopengl                  3.1.1a1             np110py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_4  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2016.10                  py27_0  
qt                        4.8.7                         4  
readline                  6.2                           2  
scikit-learn              0.17.1              np110py27_2  
scipy                     0.17.1              np110py27_1  
setuptools                27.2.0                   py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
spyking-circus            0.5.6                    py27_0    spyking-circus
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
tqdm                      4.10.0                    <pip>
tqdm                      4.11.2                   py27_0  
traitlets                 4.3.1                    py27_0  
vispy                     0.4.0.106.gf8a69d0     np110py27_0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  

Any idea?

**Comment by llobetv** [comment]
one other example, look at auto of cluster n°406, it change when i add 1 more cluster to the cross corr matrix
![image](https://user-images.githubusercontent.com/22896067/40106830-56a827f6-58e6-11e8-8339-355ab6b8b10c.png)
add 1 cluster :
![image](https://user-images.githubusercontent.com/22896067/40106844-5f29fd00-58e6-11e8-912f-5b02b0926404.png)

**Comment by nsteinme** [comment]
I think this is a bug we had before, which was - iirc - due to the way in
which phy was subselecting a number of spikes to use for these
computations, when the total number of spikes in the cluster is large. I
think we fixed it - could you check that you are using the latest version
of phy? (follow the instructions to get the "development" version here, at
the bottom: https://github.com/kwikteam/phy).

You can also try directly increasing the number of spikes used in the
computation to test whether this solves it, by changing the number here:
https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/kwik/gui.py#L396
(e.g. increase by 100x)

@rossant do you know whether the fix we made for the ccgs in templategui
was also made to the kwikgui? It looks like their ccg code is a bit
different, which seems surprising.

**Comment by nsteinme** [comment]
Great so @rossant the bug is that the updated (fixed) acg/ccg code from template-gui needs to be in kwik-gui too.

**Comment by tomasaso** [comment]
Hi Nick, 

in the message from the 16th May 2018 you suggest changing the number of spikes used for the computation of the autocorrelogram. 

Do you know where I can find that file? I found a file with the same name here: C:\Users\......\AppData\Local\conda\conda\envs\klusta\Lib\site-packages\phycontrib\kwik_gui but it does not seem to be the same. Even the folder is named differently, 

Thanks in advance!

**Comment by nsteinme** [comment]
Could you try making a new environment, and reinstalling fresh there? My best guess is that somehow you're on an old version or something, I'm not sure - @rossant would know better.

**Comment by rossant** [comment]
this is likely to be fixed in the dev branch of phy
