### ISSUE TITLE
waveform view channel labels off when zoomed out?

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#15]
Could they turn off whenever they overlap one of the waveform traces, or possibly it would be just as good if they were simply plotted behind the waveform traces? I.e. this is great:

![image](https://cloud.githubusercontent.com/assets/7590975/14066235/06702808-f43c-11e5-9855-ad5153ca4627.png)

But this is not so good:
![image](https://cloud.githubusercontent.com/assets/7590975/14066238/1b9fd598-f43c-11e5-9330-8528ce14e96e.png)

**Comment by rossant** [comment]
Yes, in the meantime you can disable the labels on [this pull request](https://github.com/kwikteam/phy/pull/683).
