### ISSUE TITLE
Amplitude View Covering Entire Dataset

### ISSUE THREAD

**Issue by DJ-Hayden** [kwikteam/phy-contrib#151]
Hello,

I've finally been able to get some spike data and am working through understanding KiloSort and Phy. I'm aware it's unwise to look at the entire length of recording on the GUI (mine is 60 continuous minutes), but is there any way for **only** the Amplitude View to cover the entire length of recording? It's generally a good measure of unit stability and I don't want to miss any deviations over time.

Regards,
Dustin

**Comment by rossant** [comment]
> P.S. Actually, now that I've played around with it, it seems like Amplitude view already does just that? In that case, which windows are updated due to the interval? Just Trace View?

yes to all!

**Comment by DJ-Hayden** [comment]
Great, thanks!
