### ISSUE TITLE
bug(?) in similarity view

### ISSUE THREAD

**Issue by aliddell** [kwikteam/phy-contrib#154]
In `TemplateController.similarity._sim_ij`:

If I understand correctly, `sims` is the max template correlation (over all templates globally) for all templates corresponding to cluster `i`.

And `_sim_ij` is returning the similarity score for _template_ `j` (as long as `j` is smaller than the number of templates) but it's being invoked for _cluster_ `j`. By the time I get to Phy, _cluster_ `j` no longer corresponds (in general) to _template_ `j`, and I am seeing clusters with multiple templates with IDs smaller than `n_templates`.

I guess that at one point new clusters (from merges or splits) were assigned IDs beginning at `n_templates + 1`, but this doesn't appear to be the case anymore.

This appears to be a bug. I've got a patch ready to go if that's the case.

**Comment by rossant** [comment]
I think this is fixed in the dev branch of phy
