### ISSUE TITLE
Lead & lag relationship in Cross-correlogram

### ISSUE THREAD

**Issue by leeccj** [kwikteam/phy-contrib#156]
Hello,

I read User's guide, but couldn't figure out myself, so I am posting here.

I am trying to distinguish a bursting activity of single neuron and synaptically connected two neurons by checking the cross-correlogram.
It would be a great help if there is a lead & lag information in the cross-correlogram. 
For example, the correlogram view of (1,2) and that of (2,1) are asymmetric in time. 
However, it is not clear if neuron 1 is leading neuron 2, or vice versa.

Thank you.

**Comment by rossant** [comment]
Now specified in the documentation: neuron 1 is leading
