### ISSUE TITLE
No phycontrib/template/backup.py in dev branch

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#158]
Pretty easy to fix, but in the dev branch (working fine for Qt5, as tested), one need to remove the reference to .backup in phycontrib/template/__init__.py, as the file is missing. Is it missing on purpose, or should the reference be removed?

**Comment by rossant** [comment]
Yes, the reference is to be removed at the moment.

I have yet to do an announcement, but I'd appreciate any further feedback for this upcoming version! In particular, I'd like to know what the most urgent bug fixes and features are for the upcoming release.
