### ISSUE TITLE
psth view

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#16]
If we're closing in on a stable version of the template gui (not sure whether that is true, but if it is - ), could we think about adding a PSTH view? This can be very simple:
- If there is a event_times.npy then this view is created. event_times is [nEvents,]. 
- It shows a PSTH and rasters within a window around the events, like this:
  ![image](https://cloud.githubusercontent.com/assets/7590975/14076704/404f6fa2-f4dc-11e5-86ee-64b639edeb2b.png)
- There is some kind of snippet and/or hotkey to control the two parameters: window size (in the screenshot, it is -0.5 to 2.5 seconds around each event) and smoothing width (the PSTH is generated by making a histogram with a very small bin size (e.g. 1ms) then convolving it with a gaussian of some width). 

We could go from there to thinking about a sensible system for the two extensions you might want: 1) support for multiple different events that you could flip between or show side-by-side; 2) support for "event labels" which tells which type of event each event_times was, i.e. if there are 200 event_times maybe 50 were for stimulus1, 50 for stimulus2, etc, and you want to show 4 traces and color the raster points accordingly. But we should have a discussion about how to implement all that sensibly if we get there.

**Comment by rossant** [comment]
Sounds good. Would you like to contribute? If so, we could try to do it in several steps:

1. You make a standalone Python function that implements this view, using matplotlib for example. I suppose it will be essentially a matter of converting your MATLAB code to Python. You could do this within a script or a notebook.

2. You integrate your code into the GUI using the API provided by phy. This should be relatively easy. The main goals would be to give feedback and polish the API through a real-world scenario. We could continue to use matplotlib instead of VisPy as a first step. We can build the hotkeys/snippets later.

3. Once the feature is working well, we can integrate it directly into phy.

**Comment by nsteinme** [comment]
Thanks for the outline of how the process would work. I'll see if I can
find time...

**Comment by MHRosenberg** [comment]
Has anyone made any progress with this project? I'm about to begin working on it. I'd prefer to help someone improve existing code rather than reinvent the wheel unnecessarily.

**Comment by rossant** [comment]
No. As discussed above a first step would be to implement a Python function drawing that plot with matplotlib.

**Comment by nsteinme** [comment]
Would be fantastic! Thanks for taking it on.

**Comment by MHRosenberg** [comment]
Cool. My plan at present is to just display PSTHs for each cluster over the course of the entire recording, enabling identification of potential drift of a unit/"neuron" from one cluster to another over time.

**Comment by nsteinme** [comment]
Cool, yes that is a good idea too! I'm not sure I would quite call it a
"PSTH" because there is no stimulus, more like just a histogram. There are
already a couple of plots that have time over the whole recording as the
x-axis, maybe it can be added to one of those? E.g. if you are using the
template-gui, it could be plotted on the existing amplitude view?

**Comment by MHRosenberg** [comment]
Ok. Thanks for the suggestions regarding the histogram! I'll try those avenues once I get IPython installed and resolve the remote display issue (I posted a separate issue about it).

**Comment by rossant** [comment]
superseded by https://github.com/cortex-lab/phy/issues/839
