### ISSUE TITLE
How to debug/step through code?

### ISSUE THREAD

**Issue by DJ-Hayden** [kwikteam/phy-contrib#161]
Hey Everyone,

This is less of an issue and more of a request/ask for help, but how do you debug and step through code for phy-contrib/template GUI? I'd like to start work on a 3D feature viewer (much like Plexon Offline Sorter) but I don't know how to enter debugging or set breakpoints in a program I call from the terminal. 

-Dustin

**Comment by alex-attinger** [comment]
Hi Dustin, I've been using the python debugger (pdb, more info e.g here: https://pythonconquerstheuniverse.wordpress.com/2009/09/10/debugging-in-python/). Import pdb and insert a pdb.set_trace() at the location you want to set a break point. Hope that helps.

**Comment by DJ-Hayden** [comment]
Hey Alex, just to clarify, I'd insert import pdb into the module I wanted to check out, insert pdb.set_trace() where I wanted it to stop, then I'd just have to call phy template_gui params.py in the normal ubuntu terminal to get a python debugger? Or does this still need to be done from within a python terminal? I'm used to Atom, PyCharm, MATLAB, Spyder, etc and programs you call from within those, so I'm not quite use to debugging when the command is called from a computer terminal (and note the python terminal).

**Comment by DJ-Hayden** [comment]
P.S. Actually, I think the link you sent describes just that! I'll close the comment once I confirm it works and let people know the step-by-step of how to debug/understand the code. Thanks!

**Comment by DJ-Hayden** [comment]
Quick update: it sort of worked. I placed a pdb.set_trace() in amplitude_histogram.py's _update() function, but the moment I click a cluster to update/trigger the code to run I get an endless loop of:

19:19:05 [W] _qt:160              QCoreApplication::exec: The event loop is already running
WARNING: QCoreApplication::exec: The event loop is already running

any idea how to fix that?

**Comment by DJ-Hayden** [comment]
I'm getting what seems to be a common error when trying to debug PyQt apps. Any call to pdb.set_trace() enters an infinite terminal loop:

QCoreApplication::exec: The event loop is already running

I've tried this (https://stackoverflow.com/questions/1736015/debugging-a-pyqt4-app) but it doesn't quite work. How are you using pdb.set_trace() for this software?

**Comment by alex-attinger** [comment]
I am assuming you are using the current version of the code (not what is coming with pip install by default?) I have observed the same when I put the set_trace into the _update function. Probably a good place to insert a set_trace would be here:  https://github.com/kwikteam/phy-contrib/blob/0ed96b48a852f66a06f62924785d39385c7fafd9/phycontrib/template/gui.py#L576 ,just before gui.show(). This will give you access to the controller. I have only just started using phy and therefore barely scratching the surface. Hope that helps!

**Comment by rossant** [comment]
There ought to be a built-in feature for this, but it's not well tested. The idea was that adding `--pdb` to the command line should make the debugger work. You can find more details here:

https://github.com/kwikteam/phy/blob/master/phy/utils/testing.py#L178

https://github.com/kwikteam/phy/blob/master/phy/__init__.py#L71

https://github.com/kwikteam/phy/blob/master/phy/utils/cli.py#L60

**Comment by DJ-Hayden** [comment]
Perhaps I'm just really bad at this, but all that seems to have done is stop pdb.set_trace() from having any effect. Running testing._enable_pdb() similarly doesn't have an effect either. To be clear I'm not married to pdb, I'm just trying to step through some code and see what values variables take while I try to make some additional plotting features. I'm happy to use whatever debugging method phy and phy-contrib used during development.

**Comment by DJ-Hayden** [comment]
Hey Everyone!

Got it to work: within the file you want to debug add:

```
import pdb
from PyQt4.QtCore import pyqtRemoveInputHook, pyqtRestoreInputHook
```
to the import statements at the top and add:
```
def start_debug():
    pyqtRemoveInputHook()
    pdb.set_trace()
```
outside of the scope of any class or function already in the file. Then all you need to do is add:
```
start_debug()
```
anywhere in your code to get an interactive PDB session. Note: this will stop the program at the pdb.set_trace() call, so you'll need to use 

```
next
```
to get back to where the start_debug() trace was called. I'm trying to figure out a way to programatically call "next" and other pdb input commands but can't quite figure that out. Once you're done debugging, type:
```
c; pyqtRestoreInputHook()
```
and everything works as expected.
