### ISSUE TITLE
Cluster quality measures in clusterView

### ISSUE THREAD

**Issue by Robertooooooo** [kwikteam/phy-contrib#163]
Hi,

I would like to have two more columns in the clusterview showing the contamination rate and cluster quality for each cluster. I put the two columns in the cluster_group.csv file but now I get the following error when I open Phy template-gui: too many values to unpack (expected 2) . I guess this would be pretty easy to implement, can you point at the direction to go? I don´t know Phyton well.

Thanks!!

**Comment by nsteinme** [comment]
Just make a different .tsv file: cluster_myQualityMeasure1.tsv and make it look like cluster_group. You will then get a "myQualityMeasure1" column in the phy gui. You may need to be on the "development version" of the phy gui - see the installation instructions on the phy main github page.

**Comment by Robertooooooo** [comment]
It works perfect! Thanks
