### ISSUE TITLE
export to template-gui format non template matching data

### ISSUE THREAD

**Issue by alejoe91** [kwikteam/phy-contrib#164]
Hi,

We are developing a framework for running quickly and easily several spike sorters (https://github.com/SpikeInterface). Now we can run klusta, mountainsort4, kilosort, ironclust, spyking-circus, and tridesclous with the same API.

I have a function that exports the data to the template-gui format [exportTpPhy](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing.py#L435-L535). 
It kind of works but I can't figure out the correct 'dummy' amplitude to use. The extracted templates are average waveforms, so they are not actual templates and the don't have an associated amplitude. I tried to set all amplitudes to 1, but the TraceView does not look correct. 

Should the amplitudes be the actual peak of the average waveform?

Thank you very much for the help!

Alessio

**Comment by rossant** [comment]
the amplitude should be 1, I'm not sure why the trace view does not look correct. How big is the difference?

**Comment by alejoe91** [comment]
Hi Cyrille, 
So the amplitudes are all ones and the templates.npy looks correct (justo loaded it in python and double checked - also the waveform view is fine).

Here are a couple of screenshots. This is simulated tetrode data:
![image](https://user-images.githubusercontent.com/17097257/54454228-47932d80-4759-11e9-8951-8b87332e82e9.png)

and a close up on the traceview:
![image](https://user-images.githubusercontent.com/17097257/54454336-82956100-4759-11e9-8e76-80c3aa9b4338.png)

It seems like the residual (which should be quite low as the simulated waveforms are all the same apart from noise) is shooting upwards. Maybe a scaling problem?

The recordings seem to be loaded correctly.

Any idea?

Thanks,
Alessio

**Comment by alejoe91** [comment]
Found the error! I was saving the actual whitening and unwhitening matrix...but since the templates are the actual mean waveforms they don't need to be unwhitened. Just saving identity matrices solved the problem :)

Thanks again! 
Alessio
