### ISSUE TITLE
Raw waveforms from DAT file not consistent with phy visualization

### ISSUE THREAD

**Issue by Bassir** [kwikteam/phy-contrib#169]
![8xoVLJU](https://user-images.githubusercontent.com/2007345/55516219-95090900-563a-11e9-988b-6c447fd07d8f.png)
I'm trying to extract the raw waveforms from kilosort2 output. I've managed to get the spike times from `spike_times.npy` and am getting 80 samples from around those spike times of the proper channel for each cluster, but [when I plot the mean waveform (across all spikes for say, cluster 90), it does not look like the same average tracing.](https://user-images.githubusercontent.com/2007345/55516219-95090900-563a-11e9-988b-6c447fd07d8f.png)

    for j=1:length(unit.spikes)
        timestamp = unit.spikes(j);
        waveforms(j,:) = mmf.Data.x(unit.channel, timestamp+wfWin(1):timestamp+wfWin(2));
    end

Any advice? Some of them look OK but most of them looking very little like what phy displays for each cluster.

**Comment by nsteinme** [comment]
Note that phy uses zero-indexing, which might be putting you on the wrong
channel or getting your spikes from the wrong unit in your matlab code. I
would try plotting the waveform from all channels for cluster 90 and 91 in
matlab to see if you can find it. Also double-check that your timestamps
are in samples, not seconds (I think you should be ok here).

**Comment by Bassir** [comment]
I've verified I'm in the right channel and getting the right spikes because the number of spikes corresponding to my units correspond exactly to what is shown in ClusterView on phy. I can output the templates and they correspond exactly to the template in phy. I'm having trouble reconciling mean raw waveform with phy.
![Screenshot_2019-04-04_14-30-43](https://user-images.githubusercontent.com/2007345/55579480-5761ba00-56e6-11e9-93ff-4dd7d2f48fd6.png)

I ultimately figured out that the issue was I was taking the best channel but not transforming it using my channel map when interfacing with the .dat file.

`channel = channel_map(bestchannel)+1`

This ultimately solved my issue. Thanks!
