### ISSUE TITLE
Cannot load phy gui

### ISSUE THREAD

**Issue by asgorin** [kwikteam/phy-contrib#172]
Hello all, 

After calling template-gui through the cmd (we have computed the clusters previously using Kilosort and then ran reztoPhy), the GUI does not appear as and the cmd just shows the following:

> 
> (phy) currentdirectory>phy template-gui params.py
> (phy) currentdirectory>

I checked the phy text document and I see the following: 

> 2019-06-05 11:58:08 [D] gui:253              Loading traces at `file.dat`.
> 2019-06-05 11:58:08 [D] gui:268              Loading amplitudes.
> 2019-06-05 11:58:09 [D] gui:277              Loading 2192148 spike clusters.
> 2019-06-05 11:58:09 [D] gui:283              Loading spike templates.
> 2019-06-05 11:58:09 [D] gui:289              Loading spike samples.
> 2019-06-05 11:58:09 [D] gui:293              Loading templates.
> 2019-06-05 11:58:09 [D] gui:299              Loading the whitening matrix.
> 2019-06-05 11:58:09 [D] gui:307              Couldn't find unwhitened templates, computing them.
> 2019-06-05 11:58:09 [D] gui:309              Inversing the whitening matrix (32, 32).
> 2019-06-05 11:58:09 [D] gui:312              Unwhitening the templates (64, 82, 32).
> 2019-06-05 11:58:09 [D] gui:321              Loading similar templates.
> 2019-06-05 11:58:09 [D] gui:326              Loading channel mapping.
> 2019-06-05 11:58:09 [D] gui:334              Loading channel positions.
> 2019-06-05 11:58:09 [D] gui:339              Loading features.
> 2019-06-05 11:58:09 [D] gui:370              Loading template features.
> 2019-06-05 11:58:10 [D] gui:424              HP filtering the data for waveforms
> 2019-06-05 11:58:10 [D] gui:453              Loading the cluster groups.
> 2019-06-05 11:58:10 [D] context:35           Create cache directory `~\.phy`.
> 2019-06-05 11:58:10 [D] context:56           Initialize joblib cache dir at `~\.phy`.
> 2019-06-05 11:58:10 [D] context:128          The file `~.phy\new_cluster_id.json` doesn't exist.
> 2019-06-05 11:58:10 [D] config:46            Load config file `~\.phy\phy_config.py`.
> 2019-06-05 11:58:10 [D] gui:428              Load the GUI state from `~\.phy\TemplateGUI\state.json`.

I've tried this with a few different files now, and it always stops at the load the GUI state. 

How should I go about fixing this? (Note I redacted directory and file names.)

Thank you.

**Comment by rossant** [comment]
This is strange. Is this with the latest release or with the development version?

**Comment by asgorin** [comment]
> This is strange. Is this with the latest release or with the development version?

It is with the latest release. I have installed that release since then on other computers of similar models and OS with no issue. 

I should mention: once before on that computer we were able to use this on a sorted data set. Since then we have run into this issue with the same and multiple other sorted data sets.

**Comment by rossant** [comment]
to reopen on the phy repo if the problem still exists with the dev branch of phy
