### ISSUE TITLE
Some thoughts (2)

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#18]
Hi again, just some thoughts on the GUI. The job achieved with phy is impressive, but I'm just writing down here ideas that may be useful for exploring template-matching data. As I'm soon done with the main code of SpyKING CIRCUS 0.3, I may start to help also with phy-contrib (once this is stable enough, but it seems to almost be the case!)
- [ ] We could click on a given point in the AmplitudeView such that it should interact with the TraceView and center it around that particular spike time.
- [x] I still think that an axis (or at least, in a more elegant manner, a scale bar) should be here for the AmplitudeView plot
- [ ] We have our "meta-merging" GUI, currently in Qt, and I'm wondering how complicated it will be to use phy instead. The best may be to directly see that with Cyrille
- [ ] We could imagine some color shaded regions in the AmplitudeView trace, corresponding to different part of the recording session/stimulation, such that it can help people to quickly see if that cells is firing at time they expect it to fire. For example, the user could provide an extra file stimulation_times.npy as a 3d array with t_start on the first column, t_stop on the second, and a digit for a label/color. Then, based on that, regions in the AmplitudeView will either be colorshaded as function of the labels, or more simpler, we can just draw a color bold line on top of the cloud of dots. This will allow user to quickly see how responses are impacted by the stimulation, if cell is firing during spontaneous activity, ...
- [x] I think that people should be able to assign arbitrary labels to neurons, such as for example 'reponding to light', 'responding to movements', ... They can be useful for further analysis
- [x] We could have an option to quickly highlight all templates that have less than X spikes? In fact, there should be a way to delete several templates at once.

**Comment by nsteinme** [comment]
Great ideas, particularly the labeled amplitudeView (and/or the pc features vs time plot view). This is very related to the idea of adding a psth view: https://github.com/kwikteam/phy-contrib/issues/16 - in that it would require the same kind of input data to do it, and it would achieve a similar function in informing you about the response properties at a very basic level. 

MInor point, I think you mean a 2d array that is shape [3, nTimes].

**Comment by yger** [comment]
Indeed, I meant a 2D array with shape [3, ntimes]. My bad, thanks for the correction! Your PSTH window #16 is also related, and we used to have that in our MATLAB GUI: psths and raster plots of the responses, from a given neuron, in response to your inputs. This is useful to visualize responses of a given neuron across several trials, and therefore to label 'reliable' or 'temporally precise' neurons. 
So I think those two approaches will be able to get all the needed information from such a 2D array with on every columns: t_start, t_stop, stim_id

**Comment by rossant** [comment]
> We could have an option to quickly highlight all templates that have less than X spikes? In fact, there should be a way to delete several templates at once.

@yger can you precise what you mean by that?

**Comment by yger** [comment]
Sure. I do not know how it is in KiloSort, maybe this is different, but with our approach, the code find templates, and then fit them onto the data. Problem is that sometimes, some templates are not very good (because estimated from too few spikes, because they can be mixtures of spikes, or simply because spike detection thresholds were too low, thus they are just noise). 
It is easy to identify such templates: they often are fitted very rarely onto the data (normal, because they are not really neurons), so they have very small firing rates. Plus, also, they tend to have very small norms. So in the MATLAB GUI, I ended up have a Button that could remove all templates, at once, that will just have few spikes. 
But in a more general manner, for the GUI, this could be good to have a way, maybe using your nice prompt, to query the templates and get a subset of them as a response. Let me explain
For example :
: get rate < 0.1 will highlight all templates with firing rate less than 0.1 Hz. This could be a selection, and then the user could delete it

: get labels = 'noise' would give you all noisy templates (or any labels decided by the user)

Of course, we must specify a subset of keywords and queries that could be made, but this is just an idea. What do you think? At the end, I think it would be good for a user, that for example created a label "respond to light", to have a way to select all those cells from the command line, for example if he want to see a combined PSTH or see any quantity only from this subgroup

**Comment by rossant** [comment]
Great idea! We could have a simple `filter` action that takes a Python string as input, and selects the corresponding clusters in the ClusterView. We'd have to add a few columns (firing rate, label, etc.). You could call this action from the snippet bar, to start with at least.

However we don't have a notion of "deleting clusters" yet (it's been requested a few times already). What we can do though is move clusters to the "noise" group.

**Comment by yger** [comment]
The filter action is exactly what I have in mind. Regarding the deletion of a selection, I'm happy for now with moving clusters to the noise group. The key point is just to isolate them from the good ones such that the user can focus himself on the good templates (and thus the noisy one should be hidden). In fact, with our Meta Merging GUI, we are already throwing away most of them, but I'm mentioning it here because this is likely that I'll try to move such a GUI into your phy framework at some point.

**Comment by nsteinme** [comment]
I can second this idea, it is true also in Kilosort that there are many low
amplitude and/or low rate templates, and the "filter" idea sounds like a
fantastic way to deal with it. I would find this really helpful. Along with
firing rate and label, one of the columns can be "peak amplitude", too?

I also like the idea of having the noise ones be hidden (maybe this would
be toggle-able) but for me this doesn't seem so critical.

**Comment by yger** [comment]
Yes, peak amplitude would be a good label. Currently, in the meta merging GUI we have in python, this is exactly the information that we are using to throw away, immediately, all small templates that are likely to be noise, and resulting of spurious fluctuations around the detection thresholds. And they can be numerous...

**Comment by OrthogoNull** [comment]
Has anyone made any progress with this project? I'm about to begin working on it. I'd prefer to help someone improve existing code rather than reinvent the wheel unnecessarily.

**Comment by rossant** [comment]
No, not yet. I wasn't able to work on the project for a while but now I'm available again. What do you want to do exactly? Feel free to share your thoughts on what and how you want to implement things before actually doing it.

**Comment by MHRosenberg** [comment]
Has anyone made any progress with this project? I'm about to begin working on it. I'd prefer to help someone improve existing code rather than reinvent the wheel unnecessarily.

**Comment by rossant** [comment]
superseded by https://github.com/cortex-lab/phy/issues/839 and https://github.com/cortex-lab/phy/issues/840, the rest is done
