### ISSUE TITLE
Error in divide with no effect ?

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#19]
The GUI is working fine, however, in the shell, I have the following error 

/home/pierre/github/phy/phy/plot/transform.py:184: RuntimeWarning: invalid value encountered in divide
  return t0 + (t1 - t0) * (arr - f0) / (f1 - f0)

I'm just reporting it here to keep it in mind, but I don't think we should worry about for now

**Comment by rossant** [comment]
Should be fixed in https://github.com/kwikteam/phy/pull/685
