### ISSUE TITLE
Amplitude mismatch between templates and raw data

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#22]
When pressing "w", the templates does not have the same scaling as the raw data. However, in our case, it should, and the mean over several whitened waveforms should be the same as the template (not normalized). Just be sure that there is not something fancy on under the carpet. I'll also double check our phy export

**Comment by nsteinme** [comment]
Ok, the answer is that templates from Kilosort are whitened (not
normalized), and simply unwhitening them makes them the same size as the
raw data. Pierre I think the questions for you are: 1) Are your templates
whitened or unwhitened? 2) Is your raw data file whitened or unwhitened? If
the answers are 1) w 2) un-w then things should be working. If those are
not your answers, then I think that is the problem.

**Comment by yger** [comment]
This is what we have. Templates are saved whitened, while raw data are not, exactly as you described. This is working fine in the MATLAB GUI, so I guess there is something wrong in my export to phy. Just to be clear, we agreed that whitening_mat.npy was the whitening matrix, not the inverse, am I right?

**Comment by yger** [comment]
Problem solved, I read the code, and I was exporting the inverse of the whitening matrix.

**Comment by nsteinme** [comment]
Oh well, in that case I don't know, sorry.

Yes. I save separately whitening_mat_inv, but I guess it is not required,
sounds like.
