### ISSUE TITLE
cli:37 error ?

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#23]
Just to give it a try, I wanted to launch the GUI on larger datasets, and it throws an error. Again, no rush, I'm just reporting in case it can help

15:20:33 [E] cli:37               An error has occurred (ValueError): insecure string pickle

**Comment by rossant** [comment]
could you use the `--debug` option to get more details?

**Comment by yger** [comment]
Sure, but how do I go from a python script such as the one you used to do before in template-gui to the --debug option? I'm not using phy as a command line... 
Can the debug option be passed to the dictionary creating the gui?

**Comment by rossant** [comment]
not sure, try something like

```python
logger = logging.getLogger('phy')
logger.handlers[0].setLevel('DEBUG')
```

or just

```python
from phy import add_default_handler
add_default_handler('DEBUG')
```

**Comment by yger** [comment]
Here is the output

Not sure how helpful this is ... The dataset has 252 electrodes and 12e6 
spikes if this can be the origin of the problem. (for smaller datasets 
with 252 channels, and few spikes, this is working)

15:38:51 [I] files:31             Launching the phy GUI...
15:38:56 [D] context:56           Initialize joblib cache dir at 
`/home/spiky/sorting/data/Steph/.phy`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_mean_masks`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_mean_features`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_mean_waveforms`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_waveform_lims`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_feature_lim`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_close_clusters`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.get_probe_depth`.
15:38:56 [D] context:80           Load memcache for 
`phy.cluster.manual.controller.spikes_per_cluster`.
15:39:06 [E] cli:37               An error has occurred (ValueError): 
insecure string pickle
15:39:06 [E] cli:37               An error has occurred (ValueError): 
insecure string pickle
15:39:06 [D] cli:40               Traceback (most recent call last):
   File "/home/spiky/.local/bin/circus-gui-python", line 9, in <module>
     load_entry_point('spyking-circus==0.3', 'console_scripts', 
'circus-gui-python')()
   File 
"/home/spiky/github/spyking-circus/circus/scripts/python_gui.py", line 
218, in main
     controller = TemplateController(**gui_params)
   File "/home/spiky/github/phy-contrib/phycontrib/template/gui.py", 
line 177, in __init__
     super(TemplateController, self).__init__()
   File "/home/spiky/github/phy/phy/cluster/manual/controller.py", line 
65, in __init__
     self._init_context()
   File "/home/spiky/github/phy-contrib/phycontrib/template/gui.py", 
line 381, in _init_context
     super(TemplateController, self)._init_context()
   File "/home/spiky/github/phy/phy/cluster/manual/controller.py", line 
132, in _init_context
     self.spikes_per_cluster = ctx.memcache(self.spikes_per_cluster)
   File "/home/spiky/github/phy/phy/io/context.py", line 98, in memcache
     cache = self.load_memcache(name)
   File "/home/spiky/github/phy/phy/io/context.py", line 82, in 
load_memcache
     cache = load(fd)
ValueError: insecure string pickle

**Comment by rossant** [comment]
can you try to delete the `.phy` subfolder and try again?
what version of python do you use?

**Comment by yger** [comment]
Ok, thanks, deleting the .phy solved ths issue. I'm using latest phy/phy-contrib versions, of course :-)

**Comment by nippoo** [comment]
This might be caused by py2/py3 incompatibilities...
