### ISSUE TITLE
y-axis in the amplitude view

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy-contrib#27]

**Comment by nsteinme** [comment]
Note that this should really be in units of µV. That means params.py has to
expand to include a "gain" term, which is what you have to multiply the
values in the data file by in order to make them µV.

**Comment by yger** [comment]
Not sure to follow. In our case, amplitudes are unitless, i.e, we are fitting amplitude*template on top of the whitened data. Of course, you can say that the template has a unit, so at the end an amplitude can be considered to be in volt (if template is without unit), but this is computed in the whitened space, so I'm not really sure how this relates to physical uV. Having a gain could be useful, but what I think we should just have for now is a y-scale bar. Are you simply unwhitening everything? Am I missing something?

**Comment by nsteinme** [comment]
You can multiply the template amplitudes (in µV - does it really change so
much whitened vs unwhitened?) by the "amplitude" values, to get the axis of
that plot into units of µV. I think this is a lot more sensible and useful.
But if there is an "amplitude" column in ClusterView that has the amplitude
in µV then that gets you most of the information so I'm ok with that as an
approximate solution. Certainly in the amplitude column of ClusterView the
amplitude should be for the unwhitened template.

**Comment by rossant** [comment]
done in the dev branch of phy
