### ISSUE TITLE
Add a few default fields in the cluster view

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy-contrib#30]
Although you can add custom fields in a plugin, we could add more fields by default. 
There shouldn't be too much of a performance hit, as we already compute and cache the mean features/waveforms/templates etc. In addition to that, all cluster statistics are cached.

@nsteinme  @yger please complete the following list:
- firing rate
- ...

Feel free to post some bits of Python code too if you want.

**Comment by yger** [comment]
I would go first for firing rate and min_peak (the minimal amplitude on a given template). Maybe something also based on the topology of the probe such as argmin_peak (either a channel number, or a x/y position)?

I'll ask around what users here would like to have (as I do not sort myself....). But even if some statistics are cached, I think it would be really great if the :filter option could trigger some custom made operations. Again, assuming we have a new vector with stimulation_times.npy telling t_start, t_stop and stimulation types (spontaneous, light, deep stimulation...), then we want to do
:filter (rate > 5) in (stimulation == 'spontaneous')  
:filter argmin_peak < 100 in (stimulation == 'deep stimulation') (to select templates in some localized space only)
:filter (rate > 5) and (mean_peak < -1) 

I think this would be fairly easy to implement, and allow custom and complex selection based on users' need.

**Comment by rossant** [comment]
Do you mean selecting particular subsets of *spikes* rather than subsets of *clusters? This would actually require major changes in the code so it won't happen any time soon. The filter action is only to select all clusters that satisfy some condition.

**Comment by yger** [comment]
No, I want to select only cluster that do match this condition, not spikes. But I mean, I would like for example to select only those that are firing during some stimulus. 
But for example, assuming you have 30min of spontaneous activity, then a bunch of stimulus. You can decide to work only on cells that are firing a lot during spontaneous activity. Thus, you want to filter clusters based on that information: not the rate over all times, but only on some intervals

**Comment by rossant** [comment]
Ah! Ok, makes sense. I'll have to think about a clean way of doing it.

**Comment by rossant** [comment]
I think this is closely related to the idea of implementing analysis functions for spike trains in phy. What you want is making these functions available in the GUI to make clever selections of clusters.

**Comment by yger** [comment]
In fact, yes... But if in theory you can give any function, I simply need some :-) But maybe there is a proper way to design something modular enough such that people an provide custom functions, working on a subset of keywords or arguments that are the one exposed by the clusters

**Comment by rossant** [comment]
done in the dev branch of phy
