### ISSUE TITLE
Is offset taken into account

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#31]
Just to be sure, because on some datasets I have a TraceView that do not make any sense. Can it be that the offset in the data file is not well taken into account?

Best

Pierre

**Comment by rossant** [comment]
I think you're right, try https://github.com/kwikteam/phy-contrib/pull/32

**Comment by yger** [comment]
Thanks a lot ! I'll give it a try tomorrow !

Pierre

Le ven. 8 avr. 2016 19:40, Cyrille Rossant <notifications@github.com> a
écrit :
