### ISSUE TITLE
Option to scale waveform with amplitudes

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#34]
Could it be possible to have an option such that in the Waveform view, individuals waveforms would be multiplied by the corresponding amplitudes in order to be properly scaled? This could be useful for visualization sometimes

**Comment by nsteinme** [comment]
I thought waveform view is showing snippets of the raw data file? Why
should you multiply by the amplitude?

**Comment by yger** [comment]
Indeed,but let me explain. I just thought that in our case, for example with a bursting neuron, that have twice the same waveform but the first being larger than the second, this would result in a single template (because of auto merges), fitted once with an amplitude slightly higher than 1 and once with an amplitude slightly less than 1. So if you just pull raw waveforms, you could see two groups of waveforms, that are in fact the same template, just scaled in amplitude. You see my point?

Best

**Comment by nsteinme** [comment]
I see, so you just want to see if they really do look like scaled versions
of each other? Ok, not a feature I'd use but I see your point. Also for
what it's worth the later spikes in a burst tend *not* to have identical
shapes, even accounting for the scaling (see Fig 5B in Henze et al 2000),
though they will be fairly similar.

Harris, K. D., Henze, D. A., Csicsvari, J., Hirase, H., & Buzsáki, G.
(2000). Accuracy of tetrode spike separation as determined by simultaneous
intracellular and extracellular measurements. Journal of Neurophysiology,
84(1), 401–414. doi:http://jn.physiology.org/cgi/content/abstract/84/1/401

**Comment by yger** [comment]
As said, this was just an idea for the GUI. I'm not really sorting myself,
so I do not even know if this is a real user case. I agree with you that it
may not be the most useful feature... I just wanted to create an issue, as
it seems easy to implement. Regarding burst, that was just an example to
illustrate the point. If your template matching algorithm scale templates
with a certain amplitude, you can just have an option (pure sanity check)
that raw snippet are all similar, when properly scaled, to the template!

2016-04-12 15:45 GMT+02:00 nsteinme <notifications@github.com>:

**Comment by rossant** [comment]
So you'd like to display `waveform/amplitude` instead of just `waveform`? Should this be an option to be turned on and off, or could it just be the only option (slightly simpler to implement)?

**Comment by rossant** [comment]
feel free to reopen in the phy repo if this is still needed
