### ISSUE TITLE
template gui: after merging, then assigning to good/mua/whatever, next selected unit should be next one in the list

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#38]
I.e. I sort by spike count. I take the next one in the list, merge it with some other units, now it is higher in the list. But if I assign to good, I don't want to now see the next one from its *current* position in the list - I want to see the next one I haven't yet considered, which is the next one from its *original* position in the list.

**Comment by rossant** [comment]
This one is a bit tricky. Maybe it should select the next one in the list, skipping all clusters that have already been visited in the current session?

**Comment by nsteinme** [comment]
Well, I'm not sure that's the best solution - a lot of times I will click around to see various clusters randomly or even go down through them all one by one before starting to do the merging stuff. 

What about this - each time you select a new cluster in ClusterView by clicking or by assigning a previous cluster to a group, it will at that moment decide what the _next_ cluster should be. Then whatever merging or whatever you do, once you now assign the "best" to some group, it will go to the "next" it had picked previously. Does that make any sense?

**Comment by cxrodgers** [comment]
I'm having a similar issue in phy kwik-gui. I agree, Nick's suggestion is exactly the "expected behavior" from my point of view.
