### ISSUE TITLE
two waveform views?

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#39]
Can I have one with waveforms not overlaid, and another at the same time that shows the templates overlaid? I switch back and forth between these a lot, it would be better just to have them both all the time.

**Comment by rossant** [comment]
@nsteinme do you feel like this can be closed? Note that it is planned to enable multiple views of the same type later, but that will be implemented in phy, not phycontrib

**Comment by nsteinme** [comment]
Hm, well, I still think this would be a useful feature. Do you mean you want to move the issue to the other repository?

**Comment by rossant** [comment]
Didn't you say earlier that it wouldn't be convenient to have 2 views for waveforms and templates?

**Comment by nsteinme** [comment]
Hmmm... yes I do remember saying that. But I was forgetting the point of this comment, which was the overlaid/non-overlaid thing. It is not a big deal, but maybe it would be a good idea to ask other users what they think about that idea (or even about what views they use or wish they had, generally).

**Comment by rossant** [comment]
done in the dev branch of phy
