### ISSUE TITLE
phy-contrib installation / kwik_gui import error

### ISSUE THREAD

**Issue by vncntprvst** [kwikteam/phy-contrib#4]
Hi there,
not sure what I'm missing in the installation procedure but something's not going right for me.
Easy install with > pip install phycontrib returns:
Collecting phycontrib   
Could not find a version that satisfies the requirement phycontrib (from versions: ) No matching distribution found for phycontrib

Advanced install: there's no plugins directory in phy. I create one, then clone the source code. I end up with a directory structure that looks like this: \phy\plugins\phy-contrib\phycontrib\
I tested import IPlugin from phy, and it works. But then calling phycontrib results in this error:
 from phycontrib.template import create_template_gui
File "C:\Anaconda\envs\spykc\lib\site-packages\phycontrib-1.0-py2.7.egg\phycontrib\__init__.py", line 16, in <module>
    from . import kwik_gui  # noqa
ImportError: cannot import name kwik_gui

Yet the kwik_gui directory is there and should be accessed.
I tried variations on directory structures, and running phy-contrib install. 

Any tip on how to get this running?

**Comment by rossant** [comment]
Ah, this is still a work in progress and not ready for public use, so the instructions are outdated, the documentation nonexistent, the pip package doesn't work yet, etc. Anyway you should be able to clone the repo and do `python setup.py develop` to get the development version. This package depends on the `kill-kwik` branch of the phy repo.

**Comment by vncntprvst** [comment]
All good now! Thanks.
