### ISSUE TITLE
in feature grid view, (0,0) is not at the center of the plot.

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#43]
It appears to be somewhere below and to the left of the center of the plot, where "center of the plot" means the location of the crosshairs.

**Comment by rossant** [comment]
can you post a screenshot?

**Comment by nsteinme** [comment]
Yeah here's one: 

![image](https://cloud.githubusercontent.com/assets/7590975/16486046/0f6881da-3eba-11e6-89f5-ed5a5be88cd3.png)

The red arrows I drew point to points that are zeroed (because they weren't in the sparse feature matrix) but they still don't show up on one of the axis lines, which proves that it's not just me being confused about what are the true values of the plotted points.
