### ISSUE TITLE
Label of 4th feature in feature view updates incorrectly

### ISSUE THREAD

**Issue by ereming** [kwikteam/phy-contrib#44]
According to the labels in the feature view, left click assigns feature 1 (indexed as 0) of the selected channel to slots 1 & 4, and feature 2 (indexed as 1) to spot 3. However, the data for slot 4 don't change. Right click seems to add feature 1 of the selected channel to slot 2, and feature 2 to slot 4. However in this case, only the data are updated, whereas the label does not. I think this is a bug and the label for slot 4 should change on right click (along with the data), but not left click.

**Comment by rossant** [comment]
this should be fixed in the dev branch of phy, reopen in the phy repo if not
