### ISSUE TITLE
template subtraction in traces view is not quite accurate

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#47]
Un-whitened templates are subtracted from the raw data for visualization, but the templates were not only whitened but also high-pass filtered. I don't think there can be any way to un-filter them, so this leads to the subtraction being imperfect. 

I guess the only options to make it accurate are: 1) Change the requirements of the template-matching software (kilosort, spyking circus) such that they go ahead and return templates that are from the raw data, not the whitened or filtered data; 2) Have the option to show the raw data whitened and filtered instead of raw. Then subtract the original (whitened) templates from it. Option 2 seems distinctly preferable, both because you might want to see the whitened/filtered data anyway, and because having the templates generated from un-filtered data would potentially introduce a lot of noise into them. But it has the problem that the filter must be specified somehow so phy can do it correctly. 

Low priority...

**Comment by yger** [comment]
In our case, we do not see the problem, as we are showing the filtered data in phy, therefore the substraction is correct. But I think having an option, if people still want to see the original datafiles, unfiltered, could be good.

**Comment by nsteinme** [comment]
Well, you just mean that you filter the data and then discard/archive the
raw data, I guess? Of course this is an option for anyone; perhaps I should
do this, too! As you say, the drawback is just that it eliminates the
option of seeing the raw data in case something looks weird.
