### ISSUE TITLE
Does phy support remote display viewing?

### ISSUE THREAD

**Issue by MHRosenberg** [kwikteam/phy-contrib#51]
I'm not immensely experienced with Ubuntu and remote access, so this may be a naive or silly question...

I am unable to run `phy template-gui params.py --debug` from a remote display. See screenshot of error message below. The identical command works fine when run from the physical machine.  

I use MobaXterm 9.0 in Windows XPS 13 to run the Matlab GUI on a labmate's Ubuntu (14.04.4 LTS x86_64) machine in another room. We have tried VNC Viewer and NoMachine but were unable to simultaneously use separate accounts on the machine: displays were either duplicated or just an empty gray screen with a cursor. 

Given that both the Matlab and Firefox GUIs work fine from MobaXterm, I thought perhaps the issue is something specific to Phy or, more likely, how I'm using it. 

Any thoughts? Thanks!

I have verified that new_cluster_id.json is in fact missing from that location (and all subdirectories), however that doesn't seem to be a problem when running from the physical Ubuntu machine.  
![phy mobaxterm error](https://cloud.githubusercontent.com/assets/20173342/16817643/8ee2c5c2-48f8-11e6-8481-6fb24585aa00.png)

**Comment by rossant** [comment]
I might be doable with some effort. The main problem is that the program uses the GPU via OpenGL so the remote display software and protocol have to support this.
