### ISSUE TITLE
amplitude view scales time incorrectly

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#55]
Amplitude view makes it so that the first spike of each cluster is at time=left edge of plot and the last is at time=right edge of plot. Instead the time axis should go from the beginning to the end of recording. E.g. here is amplitude view: 

![image](https://cloud.githubusercontent.com/assets/7590975/17038905/c9b7aab2-4f8f-11e6-851b-b48770793920.png)

And here is the same two clusters in feature view: 

![image](https://cloud.githubusercontent.com/assets/7590975/17038911/d57d8538-4f8f-11e6-87f1-b02b1d720271.png)

You can see they're misaligned relative to each other (the main group of red points comes before the blue in feature view but not in amplitude view) - it's feature view that's correct, and amplitude view is mis-scaled.

**Comment by rossant** [comment]
Fix pushed on optim, let me know if that works.

**Comment by rossant** [comment]
@nsteinme is this fixed?

**Comment by nsteinme** [comment]
Yes I think so.
