### ISSUE TITLE
clustering -> Move menu item doesn't work

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#59]
Was trying to move a cluster back to "unsorted". Put "3" in the box and pressed ok, but got: 

![image](https://cloud.githubusercontent.com/assets/7590975/18093877/54c69be2-6ec9-11e6-9af5-a9eef182c339.png)

**Comment by rossant** [comment]
If you put "47,54 3" (with the cluster id(s) first), it might work. It's a bug, because if the cluster ids are not specified, it should use the selected ones
