### ISSUE TITLE
TemplateView without raw data?

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#64]
Is is possible to get a TemplateView or something similar if raw data are not there. On my install, when raw data are not provided, I do not get the TraceView (fine), but I'm also loosing the WaveformView, and thus all info about the templates. Maybe there could at least be a TemplateView, because for template-matching algorithm, we have all the needed data to display them

**Comment by nsteinme** [comment]
Well WaveformView currently shows both templates and waveforms - so I think
all you're asking is that WaveformView still be created, just without
showing any waveform samples.

**Comment by yger** [comment]
Yes, exactly ! Because if we do not have the data as raw binary, it would
still be great to see the templates !
