### ISSUE TITLE
Dealing with non homogeneous gains for channel scaling

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#68]
I do not really even know if there is a global "gain" parameter, to properly scale the waveforms read from the raw format, but if I am assuming there is one, several questions:
- can we set it in the dictionary of parameters?
- is it possible for such a gain to be a vector of size n_channels? This is in line with the IO request that I had for dealing with multiple file format, but sometimes, every channel has its own gain...

**Comment by rossant** [comment]
I don't think we have such a gain parameter at all. Waveforms are automatically scaled in phy.

**Comment by yger** [comment]
Automatically, what does this means? Because you are reading the waveforms
from a raw binary file, you are just showing directly the content of the
file, assuming the gain to turn those numbers into uV is 1?

2016-10-06 12:34 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by rossant** [comment]
I just rescale the data so that it fits in the waveform view. Note that there is no axis in the plots yet, so the scaling value is irrelevant atm.

**Comment by yger** [comment]
Ok, but if templates are computed on scaled data, with gain taken into
account, how do you establish the match between raw waveforms and the
templates ? You don't I guess... So this is equivalent to say that you have
a fixed gain of 1 atm. But I agree that as long as you do not have
scalebars, this is rather fine




Le jeu. 6 oct. 2016 13:15, Cyrille Rossant <notifications@github.com> a
écrit :

I just rescale the data so that it fits in the waveform view. Note that
there is no axis in the plots yet, so the scaling value is irrelevant atm.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kwikteam/phy-contrib/issues/68#issuecomment-251933769>,
or mute the thread

**Comment by rossant** [comment]
I don't... but I use unwhitened templates and I think that kilosort uses a scaling factor in the provided whitening matrix...

**Comment by yger** [comment]
Yes, you are right, there is the whitening procedure in between. I do not
know what is the scaling factor you are talking about. But still, I just
want to make the point that if the GUI wants to have a scale bar, and
display channels in uV, then gain factors will be necessary. My point is
simply that they should rather be a vector of size n_channels rather than a
single value, as I'm now dealing with several file formats.

2016-10-06 13:47 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by rossant** [comment]
data * gain = uV
