### ISSUE TITLE
Arbitrary cluster labels

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy-contrib#70]
@marius10p and I were talking about how it would be helpful both for the experimenter's later use and in the service of developing better quality metrics if we had the ability to assign a more specific evaluation than just "noise", "mua", or "good". I.e. keep those existing options (and retain the special meanings of 0-3), but also have the ability to assign an arbitrary number as a group label. Maybe could be most easily implemented as a snippet: ":g 67" for instance. Any number >3 would be colored green in cluster view (or could be colored on a graded scale, relative to the max number currently in the list? that'd be cute but not very important), and anything >3 would be included in future "closest match" lists, just like Good are currently. That is, treat them just like Good. 

Hope that might be easy to implement in the short term, would be great to give it a try, there is a lot of interest in developing better quality metrics right now and this would be a really useful step towards that. The idea is you could see which objective measures can best predict these sliding-scale ratings with more confidence than just predicting a binary is-it-Good-or-not, since Good may include lots of different things. Thanks!

**Comment by rossant** [comment]
Should be doable. To be sure that I understand the use case: you want to look manually at clusters and decide how much you'd like the quality metrics to be. This cluster is excellent, should be 90, that one is good but not that good, should be 20, etc. Once you've done that, you can compare different quality metrics algorithms and find the one that is the closest to your own evaluation?

**Comment by yger** [comment]
Should those user-defined labels only be numbers? Just because I think we
already spoke about that a while ago (
https://github.com/kwikteam/phy-contrib/issues/18), but to me it would be
great to have more flexibility there and not restrict those names to
numbers: I know users that would be happy to create categories such as, for
example "cells reponding to light flashes", or more exotic tags. Of course,
a single cells could belongs to several groups. For example 'good' +
'responding to light flashes'. But maybe I'm missing your point about
quality metrics...

2016-10-13 17:04 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by rossant** [comment]
Actually the feature is already implemented. You can choose `clustering>move` and type any group you want. But the clusters won't be classified as "good" -- that's what has to be done.

**Comment by yger** [comment]
Ok, my bad. The system is such that you can have multiplie labels assigned
for one neuron, and eventually sort cells by labels? I'll have a look

2016-10-13 17:18 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by rossant** [comment]
No, you can only have one label currently. You can't sort cells by labels yet.

**Comment by nsteinme** [comment]
Yep I forgot about your suggestion, Pierre, which is indeed even more
flexible than what I proposed. In that case Cyrille maybe we can leave the
whole noise/mua/good thing all intact and untouched. The thing to add is
simply the ability to add any number of secondary labels with arbitrary
text per cluster. It could go into the csv file - each time you add a label
it just puts a tab and that label at the end of the appropriate line. So
":lab my text here" labels the currently selected one (or all currently
selected) and ":lab 541 my text" labels just 541. What about that?

In the future it would become more useful with ways to view and/or sort by
those labels. But for now just being able to add them would be great.

**Comment by rossant** [comment]
OK, but it will be much simpler to have something like `:label 541 xxx mytext` which would save the information into `cluster_xxx.csv`

**Comment by nsteinme** [comment]
Hm, I don't understand, what is "xxx" in your suggestion? You mean that you
have both labels and categories of labels? So the first category is "ids"
and maybe you have another category called "quality" and when you want to
give a quality label you say ":label 541 quality this one is great!" and
then in cluster_quality.csv you get a line that says:
541    this one is great!

? Is that what you had in mind? That sounds fine too, to me.

**Comment by rossant** [comment]
Yep. It's just that it's simpler to keep a single field in every file, especially if there's an arbitrary number of categories.

**Comment by yger** [comment]
You just also should have ways of labelling a selection of clusters easily,
but otherwise, this sounds fine to me, and easier for post-processing of
the labels.

2016-10-13 17:48 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by rossant** [comment]
Sure, if you omit the cluster indices, it will take the current selection of clusters. You can also do things like `:label 541,550,554 ...`
