### ISSUE TITLE
channel labels missing, trace view scaled weird

### ISSUE THREAD

**Issue by micheleacox** [kwikteam/phy-contrib#79]
Decent chance this is user error, but I'm at a loss as to how to resolve. When I launch Phy, neither the TraceView or ClusterView have channel labels. Further, the TraceView seems to show all the channels overlapping. 

I'm running into the same issue on 2 machines and both the KiloSort simulation data as well as data I sorted myself with KiloSort. Below is an image from the "eMouse" KiloSort simulation.

![untitled](https://cloud.githubusercontent.com/assets/7706858/19773161/1f7fe546-9c2e-11e6-8367-162c8bedda58.png)

Pretty much looks the same when I run my data (no pic here). I have a 32 channel linear array in my data, and the channel_positions.npy looks how I think it should: 

![untitled2](https://cloud.githubusercontent.com/assets/7706858/19773322/bd0b06b0-9c2e-11e6-98dd-147b0e523476.png)

This is really more of a forum issue than a bug/development issue, so please let me know if there is a more appropriate place to post / look for answers.

**Comment by rossant** [comment]
Hi, try this: press alt+down for a long time to decrease the scaling. Also you can toggle the channel labels in the menu bar.
If you still have issues, could you post here the content of `~/.phy/TemplateGUI/state.json`?

**Comment by micheleacox** [comment]
These were exactly the fixes I needed. Posting a screen shot below for other users. Thank you! 
![untitled](https://cloud.githubusercontent.com/assets/7706858/19773700/2d8e35e6-9c30-11e6-9b12-42d63c7a1223.png)
