### ISSUE TITLE
Phy Template-Gui

### ISSUE THREAD

**Issue by kkatlowitz** [kwikteam/phy-contrib#80]
Hello,

I am using kilosort with phy template gui. Occasionally (i dont know why) when I am clustering, every time I assign a cluster, the ClusterView resets the ordering of this clusters according to ID# (which is very frustrating). This issue is solved when I delete the .phy folder in Users. 
Any idea what is causing this?

**Comment by nsteinme** [comment]
I think I have seen what you are talking about and know why it happens -
can you make sure the column headings, at the top of clusterview, only show
one "sorting direction triangle"? If there are more than one of these, it
will be sorting by more than one column and you can't tell which is the
first. You can get rid of it by just sorting then re-sorting by the column
you want, i.e. just keep clicking the column you want to sort by until it
is the only one with a triangle.

**Comment by kkatlowitz** [comment]
Thanks, that seems to have fixed it.
