### ISSUE TITLE
New phy extract-waveforms command

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy-contrib#81]
New plugin: `phy extract-waveforms myfile.kwik` creates a `waveforms.npy` 3D array with the extracted waveforms of all spikes.

**Comment by nicklesica** [comment]
Hi,

Is there a way to use this command with the template-gui?

Thanks,

Nick Lesica

**Comment by rossant** [comment]
This feature is not available yet, but when I'll implement it I'll do it for the template-gui too.

**Comment by nicklesica** [comment]
OK, thanks.

**Comment by nsteinme** [comment]
Hi Nick, and for anyone else for whom this might be helpful, here's a short bit of matlab to extract waveforms - it's not as nice as a full, easy-to-use plugin, but it might get the job done in the short term. 

```
mmf = memmapfile(params.filename, 'Format', {params.dataType, [nChInFile nSamp], 'x'});

st = readNPY('spike_times.npy'); % these are in samples, not seconds
clu = readNPY('spike_clusters.npy');
theseST = st(clu==19); % spike times for cluster 19
extractST = theseST(1:min(100,length(theseST))); %extract at most the first 100 spikes
nWFsToLoad = length(extractST); 
nCh = 64; % number of channels
wfWin = [-30:30]; % samples around the spike times to load
nWFsamps = length(wfWin);
theseWF = zeros(nWFsToLoad, nCh, nWFsamps);
for i=1:nWFsToLoad
     tempWF = mmf.Data.x(1:nChInFile,extractST(i)+wfWin(1):extractST(i)+wfWin(end));
     theseWF(i,:,:) = tempWF(params.chanMap+1,:);
end
```

**Comment by nicklesica** [comment]
Thanks!

**Comment by rossant** [comment]
code given in the documentation of phy, "API examples" section
