### ISSUE TITLE
Pressing w or m seems to trigger a permutation of the channels

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#89]
It seems that displaying the mean over waveforms or the raw template are not the same for dense templates (it looks good for sparse)... It looks like there is a permutation of the channels. Can it be the case? (see the 64 channels dataset I sent you as an example).

**Comment by rossant** [comment]
Could you send me the dense file (I only have the sparse files)?

**Comment by yger** [comment]
Here you can download the dense file https://cloud.yger.net/index.php/s/n1ClhDXlZEFh1SM

**Comment by rossant** [comment]
Do you mean that between the sparse and dense versions of the same dataset, the "best" (unmasked) channels are not the same? This is indeed the case. In the sparse version, the best channels are given by the `template_ind.npy` array and they are controlled by the export function in SpykingCircus. In the dense version, the best channels are the N channels closest to the channel with the largest template amplitude. There is no reason why these two sets of best channels should be the same unless you use the same algorithm to determine the best channels in SpykingCircus.

**Comment by yger** [comment]
No this is not what I meant. This is expected, I agree. What I meant is
that when you open the dense dataset, if you press w or m (one should show
the template, and the other the mean over waveform, am i right?), then the
two plots for a given template are really different. Do you see the
problem? As if channels were permuted.. I'll send you screenshots later

Le ven. 20 janv. 2017 à 09:41, Cyrille Rossant <notifications@github.com> a
écrit :

**Comment by rossant** [comment]
Ah, ok, I see what you mean. I'll have a look...

**Comment by rossant** [comment]
Looking at the code and I can't find any obvious error...

The function that loads a template (dense-specific):
https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/template/model.py#L511

The function that loads the template waveforms (common for dense and sparse):
https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/template/gui.py#L253

Can you double-check that the data is correct? i.e. that by plotting the data directly in Python you don't obtain the same thing as phy?

**Comment by yger** [comment]
Ok, again, indeed, my mistake, I think this is a problem with my dense export, which was changed because of the sparse mode. Sorry for that
