### ISSUE TITLE
unwhiten function crashing if exporting sparse templates defined only on 1 channel?

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#90]
When some templates are loaded as sparse, the GUI is crashing. I think that it is related to the unwhiten function: if a sparse template is defined only on a single channel, is it working?

**Comment by rossant** [comment]
Again, could you send me a dataset that crashes?

**Comment by yger** [comment]
And here you can see the problem (still with the 64 channels dataset I gave you). The same templates, exported in dense (working), and sparse (crashing). The 59 last templates are not "real" templates, but rather used by our garbage collector mode to represent visually unfitted spikes, peaking next to electrode k. Therefore, in order to see those spikes with phy, I create n_elec templates defined by 0 on a single channel only. And I guess this is what crashes in the sparse mode. Dense data are there https://cloud.yger.net/index.php/s/CH4xwhTst5jY039 and sparse data  there https://cloud.yger.net/index.php/s/vQrQcPscJrrovrY

**Comment by rossant** [comment]
So the problem is that the whitening matrix is 59x59, but it is requesting channel 59 which is impossible... I guess the data is inconsistent then? phy assumes that the whitening matrix spans all channels.

**Comment by yger** [comment]
Indeed, this was a mistake from my export
