### ISSUE TITLE
Split templates based on the amplitudes

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#95]
I think I already asked that a while ago, but now that the sparse templates are working, I need to keep pushing :-) 
Would it be easy (and possible) to split a given template based on the amplitudes? I mean, to draw a polygon around a subset of the amplitudes, such that if you split if will create two templates, with amplitudes inside and outside the polygon.

**Comment by nsteinme** [comment]
Agreed this would be useful!

**Comment by rossant** [comment]
done in the dev branch of phy
